### ISSUE TITLE
virtual int parseArgs(int& argc, char **argv);

### ISSUE THREAD

**Issue by muratdemirtas** [serhmarch/ModbusTools#1]
https://github.com/serhmarch/ModbusTools/blame/e3a607349512e201bd7f4dcfc47fb27a526f3f32/src/core/core/core.h#L171

Warning: The data referred to by argc and argv must stay valid for the entire lifetime of the QApplication object. In addition, argc must be greater than zero and argv must contain at least one valid character string."

[From QT 5 Documentation](http://doc.qt.io/qt-5/qapplication.html#QApplication).

you have to change 

virtual int parseArgs(int argc, char **argv); >> virtual int parseArgs(int& argc, char **argv);

Faced issue when debug your modbus tool in linux environment.

1  strlen                                                     strlen.S 106 0x7ffff57e4b96 
2  QCoreApplication::arguments()                                           0x7ffff632b54d 
3  ??                                                                      0x7fffeed3f74f 
4  QXcbIntegration::wmClass() const                                        0x7fffeed3fc1e 
5  QXcbWindow::create()                                                    0x7fffeed540ab 
6  QXcbIntegration::createPlatformWindow(QWindow *) const                  0x7fffeed3f4c1 
7  QWindowPrivate::create(bool)                                            0x7ffff6e675dd 
8  QWidgetPrivate::create_sys(unsigned long long, bool, bool)              0x7ffff76ec893 
9  QWidget::create(unsigned long long, bool, bool)                         0x7ffff76ec019 
10 QWidget::setVisible(bool)                                               0x7ffff76f7ea2 
11 main                                                       main.cpp 13  0x409d62     

**Command line args > -gui -tray -project -singleton

works in kali linux,
thank you.**

![image](https://github.com/serhmarch/ModbusTools/assets/9981092/6676aa7d-bb80-416c-b666-b19f4248aaca)

**Comment by serhmarch** [comment]
Thank you for report. I have already fixed the problem
