### ISSUE TITLE
Error in register addressing (Send Message)

### ISSUE THREAD

**Issue by crazy4volvo** [serhmarch/ModbusTools#11]
Hello, I'm Modbus newbie so in fact I'm not sure if I'm right or wrong ;)

I'm trying to experiment with  chinese XY SK-120 DC/DC converter registers with your very useful software.
I noticed that in "Send Message" window the function "WriteSingleRegister" sends data to register address +1.
For example:
R/w registers 400001 and 400002 set voltage and current. They are read correctly, but when I try to set the voltage (reg. 400001) , the data is written to 400002 despite setting 4x and 1 in Write Data fields.  This is valid for all other register adresses I tested (backlight, on/off etc).  

Many thanks!

**Comment by serhmarch** [comment]
Yes, you're right. Wrong offset. Thank you for the report. I'll fix it in the next release

**Comment by crazy4volvo** [comment]
Thank you Serhii, take care.

**Comment by serhmarch** [comment]
Issue is fixed and new v0.3.3 release is available.

**Comment by crazy4volvo** [comment]
I confirm, works as expected.
