### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by andi-at-1** [serhmarch/ModbusTools#14]
Hi,
Got following error with actual ubuntu:

/home/user/modbustools/ModbusTools/src/core/sdk/mbcore.cpp: In function ‘QString mb::toString(Modbus::StatusCode)’:
/home/user/modbustools/ModbusTools/src/core/sdk/mbcore.cpp:308:18: error: ‘Status_BadSerialWriteTimeout’ is not a member of ‘Modbus’; did you mean ‘Status_BadSerialReadTimeout’?
  308 |     case Modbus::Status_BadSerialWriteTimeout   : return QStringLiteral("BadSerialWriteTimeout");
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  Status_BadSerialReadTimeout

i removed the line, then it compiled just fine and started.

**Comment by serhmarch** [comment]
Hello. You need to update `ModbusLib` subproject to latest version (it's 0.3.5 for now) and then try to built:
```
$ git submodule update --remote src/modbus
```
