### ISSUE TITLE
Client Scanner scans localhost

### ISSUE THREAD

**Issue by eshattow** [serhmarch/ModbusTools#15]
Hi, the Scanner apparently ignores the "Host" and "Port" settings. The log shows "TCP:localhost:502" errors no matter what is in the "Host" and "Port" settings.

**Comment by serhmarch** [comment]
Hello. Thanks for report. I have found the reason and will make update very soon.

**Comment by serhmarch** [comment]
Done. Version [v0.3.7](https://github.com/serhmarch/ModbusTools/releases/tag/v0.3.7) is available with fixed current issue.
