### ISSUE TITLE
Unable to Change Timeout Time for TCP Connection

### ISSUE THREAD

**Issue by MaxMumm** [serhmarch/ModbusTools#17]
no matter if a create a new TCO Port with a longer Timeout Time or if i edit the timeout Time of a Port, the connection will always be closed after 3 Seconds if there is no Communication.

**Comment by serhmarch** [comment]
Hello. Thanks for your bug report. I have found and fixed it. I'll update it in the next release.

**Comment by MaxMumm** [comment]
Thanks! When will the next realise be?

**Comment by serhmarch** [comment]
I think tonight

**Comment by MaxMumm** [comment]
great!

**Comment by serhmarch** [comment]
Here you go [v0.3.8](https://github.com/serhmarch/ModbusTools/releases/tag/v0.3.8)
