### ISSUE TITLE
Log Settings Not Saved

### ISSUE THREAD

**Issue by maroc81** [serhmarch/ModbusTools#8]
Changing log flags does not appear to work.  I am using the latest version and I go to Tools -> Settings -> Log and uncheck all the Log Flags except Error.  When I go back to this page all the Log Flags are checked again and the log outputs everything.  The Use Timestamp check box appears to work but none of the log flags do.

**Comment by serhmarch** [comment]
Thank you. Already fixed. Check latest release.

**Comment by maroc81** [comment]
Thank you!  I can confirm this setting is working now.  I think I'm seeing a different problem with the new build so I will create a new issue.
