### ISSUE TITLE
Different exception code in version 0.3.2

### ISSUE THREAD

**Issue by maroc81** [serhmarch/ModbusTools#9]
I'm using version 0.3.2 and got an error when trying to read from a modbus TCP device.

```
08.10.2024 16:57:22.876 'Device': Tx: 00 05 00 00 00 06 01 04 00 00 00 01 
08.10.2024 16:57:22.876 'Device': Rx: 00 05 00 00 00 03 01 84 02 
08.10.2024 16:57:22.877 'Device': Returned Modbus-exception with code 212
```

The device table "Status" column just shows a red box.   If I use an old client I get the output: `'Device': TCP. Returned Modbus-exception with code '2'` and the status column shows `BadIllegalDataAddress`.

**Comment by serhmarch** [comment]
Ok. The trouble was within `ModbusLib` sub-project. I have already fixed it and now I'm updating the latest release

**Comment by serhmarch** [comment]
Done

**Comment by maroc81** [comment]
Confirmed everything is working now as expected!  Thank you and thanks for this incredible software!
